export const themeInfo = {
  order: [],
  primary: '#1a5ecb',
  secondary: '#09fbeb',
  tertiary: '#869419',
  quaternary: '6fad25',
  bg_color: '#ffffff',
  foreground_color: '#27272a',
  font_name: 'Playfair_Display',
  font_color: '#ffffff',
  bg_image:
    'https://gjicrqpogkzojcniixqi.supabase.co/storage/v1/object/public/images/5c1f5463-8b88-4805-b614-c05b0795b5db/1744934212147-iPhone%2016%20-%2011.png',
}

export function MakeSections({ formData, socialLinks, vCardFilePath }) {
  const Sections = [
    {
      id: 291,
      created_at: '2025-04-18T01:05:08.351696+00:00',
      page: 55,
      definition: {
        username: 'Jonathon Moco',
        shadowColor: '#f89d00',
        profilePhoto:
          'https://gjicrqpogkzojcniixqi.supabase.co/storage/v1/object/public/images/5c1f5463-8b88-4805-b614-c05b0795b5db/1744938414148-lijo_44179_a_young_man_doing_a_skatboard_trick_photorealistic_49dde988-2d45-4f82-8177-f209d606e9c3.webp',
      },
      sec_type: 52,
      title: 'PopHero1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
    {
      id: 285,
      created_at: '2025-04-17T23:55:27.77478+00:00',
      page: 55,
      definition: {
        title: '68844B',
        btnColor: '#68844b',
        fontColor: '#ffffff',
        shadowColor: '#f89d00',
      },
      sec_type: 46,
      title: 'Pop Button1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
    {
      id: 286,
      created_at: '2025-04-17T23:57:19.191387+00:00',
      page: 55,
      definition: {
        iconBg: '#68844b',
        twitter: '1',
        linkedin: '1',
        instagram: '1',
        showTitles: true,
        titleColor: '#ffffff',
      },
      sec_type: 50,
      title: 'Social Apps1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
    {
      id: 288,
      created_at: '2025-04-17T23:59:42.530638+00:00',
      page: 55,
      definition: {
        email: 'hogotot440@adambra.com',
        phone: '817-395-8344',
        title: 'My Info',
        btnColor: '#54ae0a',
        location: 'Los Angeles CA',
        cardColor: '#68844b',
        fontColor: '#ffffff',
        shadowColor: '#f89d00',
      },
      sec_type: 51,
      title: 'PopContact1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
    {
      id: 287,
      created_at: '2025-04-17T23:58:25.926976+00:00',
      page: 55,
      definition: {
        title: 'FF9D00',
        btnColor: '#68844b',
        fontColor: '#ffffff',
        shadowColor: '#ffae00',
      },
      sec_type: 47,
      title: 'Pop Square Button1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
  ]

  return Sections
}

// Helper function to get a preview with dummy data
export function getPreview() {
  const Sections = [
    {
      id: 291,
      created_at: '2025-04-18T01:05:08.351696+00:00',
      page: 55,
      definition: {
        username: 'Jonathon Moco',
        shadowColor: '#f89d00',
        profilePhoto:
          'https://gjicrqpogkzojcniixqi.supabase.co/storage/v1/object/public/images/5c1f5463-8b88-4805-b614-c05b0795b5db/1744938414148-lijo_44179_a_young_man_doing_a_skatboard_trick_photorealistic_49dde988-2d45-4f82-8177-f209d606e9c3.webp',
      },
      sec_type: {
        id: 52,
        num: '',
        icon: 'RectangleStackIcon',
        name: 'PopHero',
        tags: null,
        type: '',
        status: 'active',
        version: 2,
        created_at: '2025-04-18T01:04:51.910132+00:00',
        definition: [
          {
            name: 'username',
            type: 'string',
            title: 'Username',
            description:
              'Displayed as the main heading below the profile image.',
          },
          {
            name: 'profilePhoto',
            type: 'file',
            title: 'Profile Photo URL',
            description:
              'Image URL for the profile picture. Should be a valid image link.',
          },
          {
            name: 'shadowColor',
            type: 'color',
            title: 'Shadow Color',
            default: 'black',
            description:
              'Color of the shadow around the profile image. Defaults to black.',
          },
        ],
        folder_name: 'digitalBusinessCard',
        preview_url: '',
        component_name: 'PopHero',
      },
      title: 'PopHero1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
    {
      id: 285,
      created_at: '2025-04-17T23:55:27.77478+00:00',
      page: 55,
      definition: {
        title: '68844B',
        btnColor: '#68844b',
        fontColor: '#ffffff',
        shadowColor: '#f89d00',
      },
      sec_type: {
        id: 46,
        num: '',
        icon: 'RectangleStackIcon',
        name: 'Pop Button',
        tags: null,
        type: '',
        status: 'active',
        version: 1,
        created_at: '2025-04-12T17:53:49.807749+00:00',
        definition: [
          {
            name: 'url',
            type: 'string',
            title: 'Link',
            description:
              'Link to another page, site, or document. Requires full URL path including https://.',
          },
          {
            name: 'btnColor',
            type: 'color',
            title: 'Button Color',
          },
          {
            name: 'fontColor',
            type: 'color',
            title: 'Font Color',
          },
          {
            name: 'shadowColor',
            type: 'color',
            title: 'Shadow Color',
          },
          {
            name: 'title',
            type: 'string',
            title: 'Button Text',
          },
          {
            name: 'download',
            type: 'boolean',
            title: 'Download',
          },
        ],
        folder_name: 'digitalBusinessCard',
        preview_url: '',
        component_name: 'RoundedShadowBtn',
      },
      title: 'Pop Button1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
    {
      id: 286,
      created_at: '2025-04-17T23:57:19.191387+00:00',
      page: 55,
      definition: {
        iconBg: '#68844b',
        twitter: '1',
        linkedin: '1',
        instagram: '1',
        showTitles: true,
        titleColor: '#ffffff',
      },
      sec_type: {
        id: 50,
        num: '',
        icon: 'LinkIcon',
        name: 'Social Apps',
        tags: 'Square',
        type: '',
        status: 'active',
        version: 1,
        created_at: '2025-04-12T21:24:38.724518+00:00',
        definition: [
          {
            name: 'twitter',
            type: 'string',
            title: 'twitter',
            description: 'requires full URL path including https://',
          },
          {
            name: 'linkedin',
            type: 'string',
            title: 'linkedin',
            description: 'requires full URL path including https://',
          },
          {
            name: 'instagram',
            type: 'string',
            title: 'instagram',
            description: 'requires full URL path including https://',
          },
          {
            name: 'threads',
            type: 'string',
            title: 'threads',
            description: 'requires full URL path including https://',
          },
          {
            name: 'facebook',
            type: 'string',
            title: 'facebook',
            description: 'requires full URL path including https://',
          },
          {
            name: 'tiktok',
            type: 'string',
            title: 'tiktok',
            description: 'requires full URL path including https://',
          },
          {
            name: 'github',
            type: 'string',
            title: 'github',
            description: 'requires full URL path including https://',
          },
          {
            name: 'spotify',
            type: 'string',
            title: 'spotify',
            description: 'requires full URL path including https://',
          },
          {
            name: 'showTitles',
            type: 'boolean',
            title: 'Show Titles',
            description: 'Show titles below the icons',
          },
          {
            name: 'titleColor',
            type: 'color',
            title: 'Title Color',
            description: 'Color of the titles below the icons',
          },
          {
            name: 'iconBg',
            type: 'color',
            title: 'Icon Background Color',
            description: 'Background color of the icons',
          },
        ],
        folder_name: 'digitalBusinessCard',
        preview_url: '',
        component_name: 'SocialAppsSquare',
      },
      title: 'Social Apps1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
    {
      id: 288,
      created_at: '2025-04-17T23:59:42.530638+00:00',
      page: 55,
      definition: {
        email: 'hogotot440@adambra.com',
        phone: '817-395-8344',
        title: 'My Info',
        btnColor: '#54ae0a',
        location: 'Los Angeles CA',
        cardColor: '#68844b',
        fontColor: '#ffffff',
        shadowColor: '#f89d00',
      },
      sec_type: {
        id: 51,
        num: '',
        icon: 'RectangleStackIcon',
        name: 'PopContact',
        tags: null,
        type: '',
        status: 'active',
        version: 2,
        created_at: '2025-04-17T23:08:31.735164+00:00',
        definition: [
          {
            name: 'title',
            type: 'string',
            title: 'Title',
            default: 'Contact',
            description: 'Main heading text displayed above the contact info.',
          },
          {
            name: 'email',
            type: 'string',
            title: 'Email Address',
            description: 'The email to be shown and linked via mailto.',
          },
          {
            name: 'phone',
            type: 'string',
            title: 'Phone Number',
            description: 'The phone number to be shown and linked via tel.',
          },
          {
            name: 'location',
            type: 'string',
            title: 'Location',
            description: 'Physical or general location to display.',
          },
          {
            name: 'cardColor',
            type: 'string',
            title: 'Button Background Color',
            description:
              'Background color of the contact container (can be any CSS color value).',
          },
          {
            name: 'fontColor',
            type: 'string',
            title: 'Font Color',
            description: 'Text color used for the contact container.',
          },
          {
            name: 'shadowColor',
            type: 'string',
            title: 'Shadow Color',
            default: 'black',
            description:
              'The color of the shadow around the contact block. Defaults to black.',
          },
        ],
        folder_name: 'digitalBusinessCard',
        preview_url: '',
        component_name: 'PopContact',
      },
      title: 'PopContact1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
    {
      id: 287,
      created_at: '2025-04-17T23:58:25.926976+00:00',
      page: 55,
      definition: {
        title: 'FF9D00',
        btnColor: '#68844b',
        fontColor: '#ffffff',
        shadowColor: '#ffae00',
      },
      sec_type: {
        id: 47,
        num: '',
        icon: 'LinkIcon',
        name: 'Pop Square Button',
        tags: 'Customize, Square',
        type: '',
        status: 'active',
        version: 2,
        created_at: '2025-04-12T18:18:45.360388+00:00',
        definition: [
          {
            name: 'url',
            type: 'string',
            title: 'Link',
            description:
              'Link to another page, site, or document. Requires full URL path including https://.',
          },
          {
            name: 'btnColor',
            type: 'color',
            title: 'Button Color',
          },
          {
            name: 'fontColor',
            type: 'color',
            title: 'Font Color',
          },
          {
            name: 'shadowColor',
            type: 'color',
            title: 'Shadow Color',
          },
          {
            name: 'title',
            type: 'string',
            title: 'Button Text',
          },
          {
            name: 'download',
            type: 'boolean',
            title: 'Download',
          },
        ],
        folder_name: 'digitalBusinessCard',
        preview_url: '',
        component_name: 'SquareShadowBtn',
      },
      title: 'Pop Square Button1',
      status: 'active',
      user_id: '5c1f5463-8b88-4805-b614-c05b0795b5db',
    },
  ]

  return Sections
}
