create table public.category_products (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  product_id uuid not null,
  category_id uuid null,
  constraint category_products_pkey primary key (id),
  constraint category_products_category_id_fkey foreign KEY (category_id) references categories (id),
  constraint category_products_product_id_fkey foreign KEY (product_id) references products (id)
) TABLESPACE pg_default;