create table public.contacts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  page text not null,
  name text null,
  emails jsonb null,
  numbers jsonb null,
  addresses text null,
  industry text null,
  company text null,
  role text null,
  website text null,
  instagram text null,
  facebook text null,
  linkedin text null,
  title text null,
  "imageUrl" text null,
  constraint contacts_pkey primary key (id)
) TABLESPACE pg_default;