create table public.forum_posts (
  id bigint generated by default as identity not null,
  "user" uuid not null,
  content text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  title text null,
  tags text null,
  constraint forum_posts_pkey primary key (id)
) TABLESPACE pg_default;