create table public.nav_clicks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  guest_id uuid null,
  page_id uuid null,
  section_info text null,
  constraint nav_clicks_pkey primary key (id)
) TABLESPACE pg_default;