create table public.orders (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  items jsonb null,
  user_id uuid null,
  status text null,
  total_paid double precision null,
  stripe_transaction_id text null,
  user_email text null,
  constraint Orders_pkey primary key (id)
) TABLESPACE pg_default;