create table public.profiles (
  id uuid not null,
  updated_at timestamp with time zone null default now(),
  website text null,
  theme text not null default '''light''::text'::text,
  profile_photo text null,
  phone_number text null,
  twitter text null,
  linkedin text null,
  facebook text null,
  instagram text null,
  threads text null,
  tiktok text null,
  spotify text null,
  first_name text null,
  last_name text null,
  middle_name text null,
  stripe_customer_id text null,
  company_name text null,
  company_website text null,
  full_name text null,
  avatar_url text null,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;