create table public.qr_scans (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  qr_id uuid not null default gen_random_uuid (),
  meta_data jsonb null,
  constraint qr_scans_pkey primary key (id),
  constraint qr_scans_qr_id_fkey foreign KEY (qr_id) references qr_codes (id) on delete CASCADE
) TABLESPACE pg_default;