create table public.sec_categories (
  id bigint generated by default as identity not null,
  title text null,
  "desc" text null,
  "Icon" text null,
  constraint sec_categories_pkey primary key (id)
) TABLESPACE pg_default;