create table public.sec_type_categories (
  id bigint generated by default as identity not null,
  category bigint not null,
  sec_type bigint not null,
  constraint sec_type_categories_pkey primary key (id),
  constraint sec_type_categories_category_fkey foreign KEY (category) references sec_categories (id),
  constraint sec_type_categories_sec_type_fkey foreign KEY (sec_type) references sec_type (id)
) TABLESPACE pg_default;