create table public.sec_type (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  definition jsonb null,
  name text null,
  preview_url text null,
  component_name text null,
  status text null default 'pending'::text,
  folder_name text null,
  num text null,
  type text null,
  version double precision not null default '1'::double precision,
  icon text not null default 'RectangleStackIcon'::text,
  constraint sec_type_pkey primary key (id)
) TABLESPACE pg_default;