create table public.secs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  page bigint null,
  definition jsonb not null default '{}'::jsonb,
  sec_type bigint null,
  title text null,
  status text not null default 'active'::text,
  user_id uuid null default auth.uid (),
  constraint sections_pkey primary key (id),
  constraint secs_page_fkey foreign KEY (page) references pages (id) on update CASCADE on delete CASCADE,
  constraint secs_sec_type_fkey foreign KEY (sec_type) references sec_type (id) on update CASCADE on delete CASCADE,
  constraint secs_user_id_fkey foreign KEY (user_id) references profiles (id)
) TABLESPACE pg_default;