create table public.subscription_type (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  cost_monthly real null default '0'::real,
  status text not null default 'pending'::text,
  description text null,
  cost_yearly double precision not null default '0'::double precision,
  sites_allowed bigint not null default '2'::bigint,
  designation text null,
  stripe_price_id text null,
  access_level bigint not null default '0'::bigint,
  constraint subscription_type_pkey primary key (id)
) TABLESPACE pg_default;