create table public.subscriptions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  sub_type bigint not null,
  status text null default 'active'::text,
  replaced_by bigint null,
  updated_last timestamp with time zone null default now(),
  stripe_id text not null,
  constraint subscriptions_pkey primary key (id),
  constraint subscriptions_user_id_key unique (user_id),
  constraint subscriptions_sub_type_fkey foreign KEY (sub_type) references subscription_type (id) on update CASCADE
) TABLESPACE pg_default;