create table public.user_vcards (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  path text not null,
  user_id uuid not null,
  page bigint null,
  file_name text not null,
  name text null,
  constraint user_vcard_pkey primary key (id),
  constraint user_vcard_page_key unique (page),
  constraint user_vcard_page_fkey foreign KEY (page) references pages (id),
  constraint user_vcard_user_id_fkey foreign KEY (user_id) references profiles (id)
) TABLESPACE pg_default;