create table public.vendor_category_products (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  product_id uuid not null,
  category_id uuid not null,
  constraint vendor_category_products_pkey primary key (id),
  constraint vendor_category_products_category_id_fkey foreign KEY (category_id) references vendor_categories (id) on update CASCADE on delete CASCADE,
  constraint vendor_category_products_product_id_fkey foreign KEY (product_id) references vendor_products (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;