create table public.visits (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  page bigint not null,
  guest_id uuid null,
  info text null,
  lat text null,
  lon text null,
  constraint visits_pkey primary key (id),
  constraint visits_page_fkey foreign KEY (page) references pages (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;